version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: widgets
      MYSQL_USER: user
      MYSQL_PASSWORD:

    volumes:
      - ./init:/docker-entrypoint-initdb.d
